training_type : "H1"

device_num : 1

func:
    func_type: "f2"  # f1 or f2
    domain : [0, 2]
    N : 1000 # Number of Collocation Point

model :
    model_type: "FourierFeature"  # FourierFeature, Standard, or SIREN
    num_features: 64 

optimizer:
    name: "lbfgs"
    args:
        lr: 0.1
        max_iter : 10

train_loop : 5 # To reduce oscillation
epoch: 50000

save_path: "./save_LBFGS/{}_{}_{}_{}" # Sequence : Model_type, training_type, func_type, optimizer_type
