training_type : "H1" # L2, H1, H2

device_num : 5

func:
    func_type: "f2"  # f1, f2, f3
    domain : [-1, 1]
    N : 1000 # Number of Collocation Point

model :
    model_type: "SIREN"  # FourierFeature, Standard, and SIREN
    num_features: 64 

adam_optimizer:
    args:
        lr: 1.e-5

lbfgs_optimizer:
    args:
        lr: 0.01

test_N : 100

train_loop : 20 # To reduce oscillation
epoch: 50000
change_optim_iter : 25000

save_path: "./save_FUSION/{}_{}_{}" # Sequence : Model_type, training_type, func_type
