folder_path : backup_folder/celeba
loss_type : H1
device_num : 0

epochs : 100
lr : 1.e-4

data:
  BATCH_SIZE : 48
  download_path : ./data/celeba_hq_128
  image_size: 128
  evaluation_path : ./generated_eval

model:
  hidden_dim : 64
  timesteps : 1000
  sampling_timesteps : 20
  objective : pred_x0

metrics:
  val_every : 1
  val_sample_count : 100
  val_batch : 32
  save_every : 5
