train_type : "exact" # L2, exact, cheb and FDM

device_num : 0

func_type: "Acklev" 

domain:
    x_range : [-2, 2]
    y_range : [-2, 2]
    N : 100 # Number of Collocation Point

model :
    num_features: 64 

optimizer:
  args:
    lr: 1.e-4
    
train_loop : 5 # To reduce oscillation
epoch: 200000
print_epoch : 1000
flag_point : [1.e-3, 1.e-4, 1.e-5]

save_path: "./{}_{}" # Sequence : func_type, train_type